### ISSUE TITLE
Update MANIFEST.IN with correct README's extension rst

### ISSUE THREAD

**Issue by bdabrowski** [gtaylor/django-athumb#35]
```
Downloading/unpacking django-athumb==2.4.1 (from -r ../etc/requirements.txt (line 21))
  Downloading django-athumb-2.4.1.tar.gz
  Running setup.py (path:/home/bartosz/.virtualenvs/xxxxxx/build/django-athumb/setup.py) egg_info for package django-athumb
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/bartosz/.virtualenvs/xxxxxx/build/django-athumb/setup.py", line 4, in <module>
        long_description = open('README.rst').read()
    IOError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/bartosz/.virtualenvs/xxxxxx/build/django-athumb/setup.py", line 4, in <module>

    long_description = open('README.rst').read()

IOError: [Errno 2] No such file or directory: 'README.rst'

----------------------------------------
Cleaning up...
```

**Comment by gtaylor** [comment]
D'oh! I'd accept a PR for this. Not currently using athumb, so it's very much a do-ocracy at this point.
